services:
  - type: web
    runtime: docker
    name: bouncy-castle-rag
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    runtime: docker
    name: bouncy-castle-rag-grafana
    region: oregon
    plan: free
    dockerfilePath: ./grafana/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: GF_SERVER_HTTP_PORT
        value: 3000
      - key: GF_SECURITY_ADMIN_USER
        value: admin
      - key: GF_SECURITY_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
