apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    url: postgres:5432
    database: rag_logs
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
