import json
import os
import random
import re

from tqdm.auto import tqdm

from src.evaluate import load_ground_truth
from src.llm import ask_llm, DEFAULT_OPENAI_MODEL
from src.rag import answer_question

DEFAULT_JUDGE_MODEL = DEFAULT_OPENAI_MODEL

JUDGE_SYSTEM_PROMPT = """You are an expert evaluator of RAG (Retrieval-Augmented Generation) systems.
You will be given a question, the retrieved FAQ context, and an answer generated by an LLM.
Rate the answer on two axes from 1 to 5:

1. **Relevance** — How well does the answer address the user's question?
   5 = Fully answers the question with accurate, directly useful information
   4 = Mostly answers the question, minor gaps
   3 = Partially answers but misses key points
   2 = Tangentially related but does not really answer the question
   1 = Completely irrelevant or unhelpful

2. **Faithfulness** — Does the answer stay true to the retrieved context without hallucinating?
   5 = Everything in the answer is supported by the context; no invented information
   4 = Mostly supported, minor extrapolation that is reasonable
   3 = Some unsupported claims mixed with supported ones
   2 = Answer largely diverges from or contradicts the context
   1 = Answer is fabricated or contradicts the context entirely

Return your scores as JSON only, with no additional text:
{"relevance": <1-5>, "faithfulness": <1-5>, "explanation": "<brief reason>"}"""


def evaluate_relevance(
    ground_truth=None,
    k=5,
    sample=None,
    judge_system_prompt=None,
    groq_model=None,
    openai_model=None,
    bm25_path=None,
    faiss_path=None,
    docs_path=None,
):
    if ground_truth is None:
        ground_truth = load_ground_truth()

    if judge_system_prompt is None:
        judge_system_prompt = JUDGE_SYSTEM_PROMPT
    if openai_model is None:
        openai_model = DEFAULT_JUDGE_MODEL

    items = list(ground_truth)
    if sample is not None:
        items = random.sample(items, min(sample, len(items)))

    scores = []

    for item in tqdm(items, desc="Evaluating"):
        question = item["question"]
        doc_id = item["document_id"]

        try:
            rag_result = answer_question(
                question,
                k=k,
                bm25_path=bm25_path,
                faiss_path=faiss_path,
                docs_path=docs_path,
                groq_model=groq_model,
                openai_model=openai_model,
            )
        except Exception:
            scores.append({
                "question": question,
                "document_id": doc_id,
                "relevance": None,
                "faithfulness": None,
                "explanation": "RAG pipeline failed",
                "rag_cost": None,
                "judge_cost": None,
                "judge_latency": None,
                "judge_tokens": None,
                "error": True,
            })
            continue

        context_text = "\n\n".join(
            f"[{ctx['category']}] {ctx['question']}\n{ctx['answer']}"
            for ctx in rag_result["contexts"]
        )

        user_message = (
            f"Question: {question}\n\n"
            f"Retrieved context:\n{context_text}\n\n"
            f"Answer: {rag_result['answer']}"
        )

        try:
            judge_result = ask_llm(
                system_prompt=judge_system_prompt,
                user_message=user_message,
                groq_model=groq_model,
                openai_model=openai_model,
            )
            parsed = _parse_scores(judge_result["response"])
            scores.append({
                "question": question,
                "document_id": doc_id,
                "answer": rag_result["answer"],
                "contexts": rag_result["contexts"],
                "relevance": parsed["relevance"],
                "faithfulness": parsed["faithfulness"],
                "explanation": parsed.get("explanation", ""),
                "judge_provider": judge_result["provider"],
                "judge_model": judge_result["model"],
                "rag_provider": rag_result["provider"],
                "rag_model": rag_result["model"],
                "rag_latency": rag_result["latency"],
                "rag_tokens": rag_result["tokens"],
                "rag_cost": rag_result["cost"],
                "judge_cost": judge_result["cost"],
                "judge_latency": judge_result["latency"],
                "judge_tokens": judge_result["tokens"],
                "error": False,
            })
        except Exception:
            scores.append({
                "question": question,
                "document_id": doc_id,
                "answer": rag_result["answer"],
                "contexts": rag_result["contexts"],
                "relevance": None,
                "faithfulness": None,
                "explanation": "Judge LLM call failed",
                "rag_cost": rag_result["cost"],
                "judge_cost": None,
                "judge_latency": None,
                "judge_tokens": None,
                "error": True,
            })

    valid = [s for s in scores if not s["error"]]
    n = len(scores)
    n_valid = len(valid)

    if n_valid == 0:
        return {
            "mean_relevance": None,
            "mean_faithfulness": None,
            "n": n,
            "n_valid": 0,
            "distribution": {},
            "total_rag_cost": 0.0,
            "total_judge_cost": 0.0,
            "total_cost": 0.0,
            "mean_rag_cost": None,
            "mean_judge_cost": None,
            "details": scores,
        }

    rel_scores = [s["relevance"] for s in valid]
    faith_scores = [s["faithfulness"] for s in valid]
    rag_costs = [s["rag_cost"] for s in valid]
    judge_costs = [s["judge_cost"] for s in valid]

    dist_rel = {i: rel_scores.count(i) for i in range(1, 6)}
    dist_faith = {i: faith_scores.count(i) for i in range(1, 6)}

    total_rag_cost = sum(rag_costs)
    total_judge_cost = sum(judge_costs)

    return {
        "mean_relevance": round(sum(rel_scores) / n_valid, 2),
        "mean_faithfulness": round(sum(faith_scores) / n_valid, 2),
        "n": n,
        "n_valid": n_valid,
        "distribution": {
            "relevance": dist_rel,
            "faithfulness": dist_faith,
        },
        "total_rag_cost": round(total_rag_cost, 6),
        "total_judge_cost": round(total_judge_cost, 6),
        "total_cost": round(total_rag_cost + total_judge_cost, 6),
        "mean_rag_cost": round(total_rag_cost / n_valid, 6) if n_valid else None,
        "mean_judge_cost": round(total_judge_cost / n_valid, 6) if n_valid else None,
        "details": scores,
    }


def _parse_scores(response_text):
    text = response_text.strip()
    json_match = re.search(r"\{.*\}", text, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group())
        except json.JSONDecodeError:
            pass
    return {"relevance": None, "faithfulness": None, "explanation": "Could not parse scores"}
